-- MySQL Script generated by MySQL Workbench
-- 08/15/14 10:49:57
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mfast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mfast` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mfast` ;

-- -----------------------------------------------------
-- Table `mfast`.`Therapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Therapist` (
  `therapistId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`therapistId`),
  UNIQUE INDEX `therapistId_UNIQUE` (`therapistId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`patientGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`patientGroup` (
  `patientGroupId` INT NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(45) NULL,
  `groupDescription` VARCHAR(128) NULL,
  PRIMARY KEY (`patientGroupId`),
  UNIQUE INDEX `patientGroupId_UNIQUE` (`patientGroupId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Patient` (
  `patientId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `gender` VARCHAR(8) NOT NULL,
  `therapistId` INT NOT NULL,
  `handDominance` VARCHAR(8) NOT NULL,
  `patientGroupId` INT NOT NULL,
  `customPatientId` VARCHAR(45) NOT NULL,
  `rightStern2acJointLength` FLOAT NULL,
  `leftStern2acJointLength` FLOAT NULL,
  `rightUpperArmLength` FLOAT NULL,
  `leftUpperArmLength` FLOAT NULL,
  `rightForearmLength` FLOAT NULL,
  `leftForearmLength` FLOAT NULL,
  `rightArmLength` FLOAT NULL,
  `leftArmLength` FLOAT NULL,
  `height` FLOAT NULL,
  `weight` FLOAT NULL,
  `notes` VARCHAR(150) NULL,
  `patientSecondGroupId1` INT NULL,
  `patientSecondGroupId2` INT NULL,
  `patientSecondGroupId3` INT NULL,
  `patientSecondGroupId4` INT NULL,
  PRIMARY KEY (`patientId`),
  UNIQUE INDEX `patientId_UNIQUE` (`patientId` ASC),
  INDEX `patientGroupId_idx` (`patientGroupId` ASC),
  INDEX `therapistId_idx` (`therapistId` ASC),
  CONSTRAINT `therapistId`
    FOREIGN KEY (`therapistId`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `patientGroupId`
    FOREIGN KEY (`patientGroupId`)
    REFERENCES `mfast`.`patientGroup` (`patientGroupId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Evaluations` (
  `evaluationId` INT NOT NULL,
  `evaluationName` VARCHAR(30) NOT NULL,
  `evaluationDescription` VARCHAR(100) NULL,
  PRIMARY KEY (`evaluationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`MeasurementSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`MeasurementSession` (
  `measurementSessionId` INT NOT NULL AUTO_INCREMENT,
  `evaluationId` INT NULL,
  `sessionPatientId` INT NOT NULL,
  `sessionTherapistId` INT NOT NULL,
  `timestamp` TIMESTAMP NULL,
  `isCompleted` TINYINT(1) NULL DEFAULT FALSE,
  `weight` FLOAT NULL,
  `level` VARCHAR(45) NULL,
  `clientVersion` VARCHAR(10) NULL,
  `optionalParams` VARCHAR(45) NULL,
  `frameCount` INT NULL,
  `sessionStatus` VARCHAR(60) NULL,
  PRIMARY KEY (`measurementSessionId`),
  INDEX `patientId_idx` (`sessionPatientId` ASC),
  INDEX `therapistId_idx` (`sessionTherapistId` ASC),
  UNIQUE INDEX `measurementSessionId_UNIQUE` (`measurementSessionId` ASC),
  INDEX `evaluationId_idx` (`evaluationId` ASC),
  CONSTRAINT `sessionPatientId`
    FOREIGN KEY (`sessionPatientId`)
    REFERENCES `mfast`.`Patient` (`patientId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `sessionTherapistId`
    FOREIGN KEY (`sessionTherapistId`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `evaluationId`
    FOREIGN KEY (`evaluationId`)
    REFERENCES `mfast`.`Evaluations` (`evaluationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`MeasurementFrame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`MeasurementFrame` (
  `measurementFrameId` INT NOT NULL AUTO_INCREMENT,
  `frameNumber` INT NOT NULL,
  `frameTime` DOUBLE NOT NULL,
  `skeletonCount` INT NOT NULL,
  `measurementSessionId` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`measurementFrameId`),
  INDEX `measurementSessionId_idx` (`measurementSessionId` ASC),
  UNIQUE INDEX `measurementFrameId_UNIQUE` (`measurementFrameId` ASC),
  CONSTRAINT `measurementSessionId`
    FOREIGN KEY (`measurementSessionId`)
    REFERENCES `mfast`.`MeasurementSession` (`measurementSessionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Skeleton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Skeleton` (
  `skeletonId` INT NOT NULL AUTO_INCREMENT,
  `measurementFrameId` INT NULL,
  `skeletonSequenceNumber` INT NULL,
  `headX` DOUBLE NULL DEFAULT 0.0,
  `headY` DOUBLE NULL DEFAULT 0.0,
  `headZ` DOUBLE NULL DEFAULT 0.0,
  `hipCenterX` DOUBLE NULL DEFAULT 0.0,
  `hipCenterY` DOUBLE NULL DEFAULT 0.0,
  `hipCenterZ` DOUBLE NULL,
  `leftAnkleX` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleY` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleZ` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleX` DOUBLE NULL,
  `rightAnkleY` DOUBLE NULL,
  `rightAnkleZ` DOUBLE NULL,
  `leftElbowX` DOUBLE NULL DEFAULT 0.0,
  `leftElbowY` DOUBLE NULL DEFAULT 0.0,
  `leftElbowZ` DOUBLE NULL DEFAULT 0.0,
  `rightElbowX` DOUBLE NULL,
  `rightElbowY` DOUBLE NULL,
  `rightElbowZ` DOUBLE NULL,
  `leftFootX` DOUBLE NULL DEFAULT 0.0,
  `leftFootY` DOUBLE NULL DEFAULT 0.0,
  `leftFootZ` DOUBLE NULL DEFAULT 0.0,
  `rightFootX` DOUBLE NULL DEFAULT 0.0,
  `rightFootY` DOUBLE NULL DEFAULT 0.0,
  `rightFootZ` DOUBLE NULL DEFAULT 0.0,
  `leftHandX` DOUBLE NULL DEFAULT 0.0,
  `leftHandY` DOUBLE NULL DEFAULT 0.0,
  `leftHandZ` DOUBLE NULL DEFAULT 0.0,
  `rightHandX` DOUBLE NULL DEFAULT 0.0,
  `rightHandY` DOUBLE NULL DEFAULT 0.0,
  `rightHandZ` DOUBLE NULL DEFAULT 0.0,
  `leftHipX` DOUBLE NULL DEFAULT 0.0,
  `leftHipY` DOUBLE NULL DEFAULT 0.0,
  `leftHipZ` DOUBLE NULL DEFAULT 0.0,
  `rightHipX` DOUBLE NULL DEFAULT 0.0,
  `rightHipY` DOUBLE NULL DEFAULT 0.0,
  `rightHipZ` DOUBLE NULL DEFAULT 0.0,
  `leftKneeX` DOUBLE NULL DEFAULT 0.0,
  `leftKneeY` DOUBLE NULL DEFAULT 0.0,
  `leftKneeZ` DOUBLE NULL DEFAULT 0.0,
  `rightKneeX` DOUBLE NULL DEFAULT 0.0,
  `rightKneeY` DOUBLE NULL DEFAULT 0.0,
  `rightKneeZ` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderX` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderY` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderX` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderY` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `leftWristX` DOUBLE NULL DEFAULT 0.0,
  `leftWristY` DOUBLE NULL DEFAULT 0.0,
  `leftWristZ` DOUBLE NULL DEFAULT 0.0,
  `rightWristX` DOUBLE NULL DEFAULT 0.0,
  `rightWristY` DOUBLE NULL DEFAULT 0.0,
  `rightWristZ` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterX` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterY` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterZ` DOUBLE NULL DEFAULT 0.0,
  `spineX` DOUBLE NULL DEFAULT 0.0,
  `spineY` DOUBLE NULL DEFAULT 0.0,
  `spineZ` DOUBLE NULL DEFAULT 0.0,
  PRIMARY KEY (`skeletonId`),
  INDEX `measurementFrameId_idx` (`measurementFrameId` ASC),
  UNIQUE INDEX `skeletonId_UNIQUE` (`skeletonId` ASC),
  CONSTRAINT `measurementFrameId`
    FOREIGN KEY (`measurementFrameId`)
    REFERENCES `mfast`.`MeasurementFrame` (`measurementFrameId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`LoginSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`LoginSession` (
  `loginSessionId` INT NOT NULL AUTO_INCREMENT,
  `LoginSessionActive` TINYINT(1) NOT NULL DEFAULT FALSE,
  `LoginSessionLastActivityTS` TIMESTAMP NOT NULL,
  `LoggedInTherapist` INT NULL,
  PRIMARY KEY (`loginSessionId`),
  UNIQUE INDEX `loginSessionId_UNIQUE` (`loginSessionId` ASC),
  INDEX `loggedInTherapist_idx` (`LoggedInTherapist` ASC),
  CONSTRAINT `loggedInTherapist`
    FOREIGN KEY (`LoggedInTherapist`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
