-- MySQL Script generated by MySQL Workbench
-- 10/23/14 10:00:16
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mfast
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mfast` DEFAULT CHARACTER SET utf8 ;
USE `mfast` ;

-- -----------------------------------------------------
-- Table `mfast`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Location` (
  `locationId` INT NOT NULL,
  `locationName` VARCHAR(45) NOT NULL,
  `locationDescription` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`locationId`),
  UNIQUE INDEX `locationId_UNIQUE` (`locationId` ASC, `locationName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Therapist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Therapist` (
  `therapistId` INT NOT NULL AUTO_INCREMENT,
  `locationId` INT NOT NULL DEFAULT 0,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`therapistId`),
  UNIQUE INDEX `therapistId_UNIQUE` (`therapistId` ASC),
  INDEX `locationId_idx` (`locationId` ASC),
  CONSTRAINT `locationId_therapist_fk`
    FOREIGN KEY (`locationId`)
    REFERENCES `mfast`.`Location` (`locationId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`patientGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`patientGroup` (
  `patientGroupId` INT NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(45) NOT NULL,
  `customGroupId` VARCHAR(45) NULL DEFAULT NULL,
  `groupDescription` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`patientGroupId`),
  UNIQUE INDEX `patientGroupId_UNIQUE` (`patientGroupId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Patient` (
  `patientId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `gender` VARCHAR(8) NOT NULL,
  `therapistId` INT NOT NULL,
  `locationId` INT NOT NULL DEFAULT 0,
  `handDominance` VARCHAR(8) NOT NULL,
  `patientGroupId` INT NOT NULL,
  `customPatientId` VARCHAR(45) NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  `rightStern2acJointLength` FLOAT NULL DEFAULT NULL,
  `leftStern2acJointLength` FLOAT NULL DEFAULT NULL,
  `rightUpperArmLength` FLOAT NULL DEFAULT NULL,
  `leftUpperArmLength` FLOAT NULL DEFAULT NULL,
  `rightForearmLength` FLOAT NULL DEFAULT NULL,
  `leftForearmLength` FLOAT NULL DEFAULT NULL,
  `rightArmLength` FLOAT NULL DEFAULT NULL,
  `leftArmLength` FLOAT NULL DEFAULT NULL,
  `height` FLOAT NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT NULL,
  `notes` VARCHAR(150) NULL DEFAULT NULL,
  `patientSecondGroupId1` INT NULL DEFAULT NULL,
  `patientSecondGroupId2` INT NULL DEFAULT NULL,
  `patientSecondGroupId3` INT NULL DEFAULT NULL,
  `patientSecondGroupId4` INT NULL DEFAULT NULL,
  PRIMARY KEY (`patientId`),
  UNIQUE INDEX `patientId_UNIQUE` (`patientId` ASC),
  INDEX `patientGroupId_idx` (`patientGroupId` ASC),
  INDEX `therapistId_idx` (`therapistId` ASC),
  INDEX `locationId_idx` (`locationId` ASC),
  CONSTRAINT `therapistId_patient_fk`
    FOREIGN KEY (`therapistId`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `locationId_patient_fk`
    FOREIGN KEY (`locationId`)
    REFERENCES `mfast`.`Location` (`locationId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `patientGroupId_patient_fk`
    FOREIGN KEY (`patientGroupId`)
    REFERENCES `mfast`.`patientGroup` (`patientGroupId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Evaluations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Evaluations` (
  `evaluationId` INT NOT NULL,
  `evaluationName` VARCHAR(30) NOT NULL,
  `evaluationDescription` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`evaluationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`MeasurementSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`MeasurementSession` (
  `measurementSessionId` INT NOT NULL AUTO_INCREMENT,
  `evaluationId` INT NULL DEFAULT NULL,
  `sessionLocationId` INT NOT NULL DEFAULT 0,
  `sessionPatientId` INT NOT NULL,
  `sessionTherapistId` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `isCompleted` TINYINT(1) NULL DEFAULT FALSE,
  `weight` FLOAT NULL DEFAULT NULL,
  `level` TINYINT(1) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `clientVersion` VARCHAR(10) NULL DEFAULT NULL,
  `optionalParams` VARCHAR(45) NULL DEFAULT NULL,
  `frameCount` INT NULL DEFAULT NULL,
  `sessionStatus` VARCHAR(60) NULL DEFAULT NULL,
  `notes` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`measurementSessionId`),
  UNIQUE INDEX `measurementSessionId_UNIQUE` (`measurementSessionId` ASC),
  INDEX `patientId_idx` (`sessionPatientId` ASC),
  INDEX `therapistId_idx` (`sessionTherapistId` ASC),
  INDEX `locationId_idx` (`sessionLocationId` ASC),
  INDEX `evaluationId_idx` (`evaluationId` ASC),
  CONSTRAINT `sessionPatientId`
    FOREIGN KEY (`sessionPatientId`)
    REFERENCES `mfast`.`Patient` (`patientId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `sessionTherapistId`
    FOREIGN KEY (`sessionTherapistId`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `sessionLocationId`
    FOREIGN KEY (`sessionLocationId`)
    REFERENCES `mfast`.`Location` (`locationId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `evaluationId`
    FOREIGN KEY (`evaluationId`)
    REFERENCES `mfast`.`Evaluations` (`evaluationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`MeasurementFrame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`MeasurementFrame` (
  `measurementFrameId` INT NOT NULL AUTO_INCREMENT,
  `frameNumber` INT NOT NULL,
  `frameTime` DOUBLE NOT NULL,
  `realTimeStampSeconds` INT(11) NOT NULL,
  `realTimeStampMicros` INT(11) NOT NULL,
  `skeletonCount` INT NOT NULL,
  `measurementSessionId` INT NOT NULL,
  PRIMARY KEY (`measurementFrameId`),
  INDEX `measurementSessionId_idx` (`measurementSessionId` ASC),
  UNIQUE INDEX `measurementFrameId_UNIQUE` (`measurementFrameId` ASC),
  CONSTRAINT `measurementSessionId`
    FOREIGN KEY (`measurementSessionId`)
    REFERENCES `mfast`.`MeasurementSession` (`measurementSessionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Skeleton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Skeleton` (
  `skeletonId` INT NOT NULL AUTO_INCREMENT,
  `measurementFrameId` INT NULL DEFAULT NULL,
  `skeletonSequenceNumber` INT NULL DEFAULT NULL,
  `headX` DOUBLE NULL DEFAULT 0.0,
  `headY` DOUBLE NULL DEFAULT 0.0,
  `headZ` DOUBLE NULL DEFAULT 0.0,
  `hipCenterX` DOUBLE NULL DEFAULT 0.0,
  `hipCenterY` DOUBLE NULL DEFAULT 0.0,
  `hipCenterZ` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleX` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleY` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleZ` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleX` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleY` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleZ` DOUBLE NULL DEFAULT 0.0,
  `leftElbowX` DOUBLE NULL DEFAULT 0.0,
  `leftElbowY` DOUBLE NULL DEFAULT 0.0,
  `leftElbowZ` DOUBLE NULL DEFAULT 0.0,
  `rightElbowX` DOUBLE NULL DEFAULT 0.0,
  `rightElbowY` DOUBLE NULL DEFAULT 0.0,
  `rightElbowZ` DOUBLE NULL DEFAULT 0.0,
  `leftFootX` DOUBLE NULL DEFAULT 0.0,
  `leftFootY` DOUBLE NULL DEFAULT 0.0,
  `leftFootZ` DOUBLE NULL DEFAULT 0.0,
  `rightFootX` DOUBLE NULL DEFAULT 0.0,
  `rightFootY` DOUBLE NULL DEFAULT 0.0,
  `rightFootZ` DOUBLE NULL DEFAULT 0.0,
  `leftHandX` DOUBLE NULL DEFAULT 0.0,
  `leftHandY` DOUBLE NULL DEFAULT 0.0,
  `leftHandZ` DOUBLE NULL DEFAULT 0.0,
  `rightHandX` DOUBLE NULL DEFAULT 0.0,
  `rightHandY` DOUBLE NULL DEFAULT 0.0,
  `rightHandZ` DOUBLE NULL DEFAULT 0.0,
  `leftHipX` DOUBLE NULL DEFAULT 0.0,
  `leftHipY` DOUBLE NULL DEFAULT 0.0,
  `leftHipZ` DOUBLE NULL DEFAULT 0.0,
  `rightHipX` DOUBLE NULL DEFAULT 0.0,
  `rightHipY` DOUBLE NULL DEFAULT 0.0,
  `rightHipZ` DOUBLE NULL DEFAULT 0.0,
  `leftKneeX` DOUBLE NULL DEFAULT 0.0,
  `leftKneeY` DOUBLE NULL DEFAULT 0.0,
  `leftKneeZ` DOUBLE NULL DEFAULT 0.0,
  `rightKneeX` DOUBLE NULL DEFAULT 0.0,
  `rightKneeY` DOUBLE NULL DEFAULT 0.0,
  `rightKneeZ` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderX` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderY` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderX` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderY` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `leftWristX` DOUBLE NULL DEFAULT 0.0,
  `leftWristY` DOUBLE NULL DEFAULT 0.0,
  `leftWristZ` DOUBLE NULL DEFAULT 0.0,
  `rightWristX` DOUBLE NULL DEFAULT 0.0,
  `rightWristY` DOUBLE NULL DEFAULT 0.0,
  `rightWristZ` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterX` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterY` DOUBLE NULL DEFAULT 0.0,
  `shoulderCenterZ` DOUBLE NULL DEFAULT 0.0,
  `spineX` DOUBLE NULL DEFAULT 0.0,
  `spineY` DOUBLE NULL DEFAULT 0.0,
  `spineZ` DOUBLE NULL DEFAULT 0.0,
  PRIMARY KEY (`skeletonId`),
  INDEX `measurementFrameId_idx` (`measurementFrameId` ASC),
  UNIQUE INDEX `skeletonId_UNIQUE` (`skeletonId` ASC),
  CONSTRAINT `measurementFrameId`
    FOREIGN KEY (`measurementFrameId`)
    REFERENCES `mfast`.`MeasurementFrame` (`measurementFrameId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`LoginSession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`LoginSession` (
  `loginSessionId` INT NOT NULL AUTO_INCREMENT,
  `LoginSessionActive` TINYINT(1) NOT NULL DEFAULT FALSE,
  `LoginSessionStartActivityTS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LoginSessionLastActivityTS` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LoggedInTherapist` INT NULL DEFAULT NULL,
  `LoggedInLocation` INT NULL DEFAULT 0,
  `LoginSessioncol` VARCHAR(45) NULL,
  PRIMARY KEY (`loginSessionId`),
  UNIQUE INDEX `loginSessionId_UNIQUE` (`loginSessionId` ASC),
  INDEX `loggedInTherapist_idx` (`LoggedInTherapist` ASC),
  INDEX `LoggedInLocation` (`LoggedInLocation` ASC),
  CONSTRAINT `loggedInTherapist`
    FOREIGN KEY (`LoggedInTherapist`)
    REFERENCES `mfast`.`Therapist` (`therapistId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LoggedInLocation`
    FOREIGN KEY (`LoggedInLocation`)
    REFERENCES `mfast`.`Location` (`locationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Results` (
  `resultsId` INT NOT NULL AUTO_INCREMENT,
  `measurementSessionId` INT NOT NULL,
  PRIMARY KEY (`resultsId`),
  UNIQUE INDEX `resultsId_UNIQUE` (`resultsId` ASC),
  INDEX `measurementSessionId_idx` (`measurementSessionId` ASC),
  CONSTRAINT `resultsSessionId`
    FOREIGN KEY (`measurementSessionId`)
    REFERENCES `mfast`.`MeasurementSession` (`measurementSessionId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Scores` (
  `scoreId` INT NOT NULL AUTO_INCREMENT,
  `resultsId` INT NOT NULL,
  `scoreName` VARCHAR(120) NULL DEFAULT NULL,
  `ScoreValue` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`scoreId`),
  UNIQUE INDEX `scoreId_UNIQUE` (`scoreId` ASC),
  INDEX `resultsId_idx` (`resultsId` ASC),
  CONSTRAINT `scoresResultsId`
    FOREIGN KEY (`resultsId`)
    REFERENCES `mfast`.`Results` (`resultsId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Skeleton_v2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Skeleton_v2` (
  `skeletonId` INT NOT NULL AUTO_INCREMENT,
  `measurementFrameId` INT NULL DEFAULT NULL,
  `skeletonSequenceNumber` INT NULL DEFAULT NULL,
  `spineBaseX` DOUBLE NULL DEFAULT 0.0,
  `spineBaseY` DOUBLE NULL DEFAULT 0.0,
  `spineBaseZ` DOUBLE NULL DEFAULT 0.0,
  `spineMidX` DOUBLE NULL DEFAULT 0.0,
  `spineMidY` DOUBLE NULL DEFAULT 0.0,
  `spineMidZ` DOUBLE NULL DEFAULT 0.0,
  `neckX` DOUBLE NULL DEFAULT 0.0,
  `neckY` DOUBLE NULL DEFAULT 0.0,
  `neckZ` DOUBLE NULL DEFAULT 0.0,
  `headX` DOUBLE NULL DEFAULT 0.0,
  `headY` DOUBLE NULL DEFAULT 0.0,
  `headZ` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderX` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderY` DOUBLE NULL DEFAULT 0.0,
  `leftShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `leftElbowX` DOUBLE NULL DEFAULT 0.0,
  `leftElbowY` DOUBLE NULL DEFAULT 0.0,
  `leftElbowZ` DOUBLE NULL DEFAULT 0.0,
  `leftWristX` DOUBLE NULL DEFAULT 0.0,
  `leftWristY` DOUBLE NULL DEFAULT 0.0,
  `leftWristZ` DOUBLE NULL DEFAULT 0.0,
  `leftHandX` DOUBLE NULL DEFAULT 0.0,
  `leftHandY` DOUBLE NULL DEFAULT 0.0,
  `leftHandZ` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderX` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderY` DOUBLE NULL DEFAULT 0.0,
  `rightShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `rightElbowX` DOUBLE NULL DEFAULT 0.0,
  `rightElbowY` DOUBLE NULL DEFAULT 0.0,
  `rightElbowZ` DOUBLE NULL DEFAULT 0.0,
  `rightWristX` DOUBLE NULL DEFAULT 0.0,
  `rightWristY` DOUBLE NULL DEFAULT 0.0,
  `rightWristZ` DOUBLE NULL DEFAULT 0.0,
  `rightHandX` DOUBLE NULL DEFAULT 0.0,
  `rightHandY` DOUBLE NULL DEFAULT 0.0,
  `rightHandZ` DOUBLE NULL DEFAULT 0.0,
  `leftHipX` DOUBLE NULL DEFAULT 0.0,
  `leftHipY` DOUBLE NULL DEFAULT 0.0,
  `leftHipZ` DOUBLE NULL DEFAULT 0.0,
  `leftKneeX` DOUBLE NULL DEFAULT 0.0,
  `leftKneeY` DOUBLE NULL DEFAULT 0.0,
  `leftKneeZ` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleX` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleY` DOUBLE NULL DEFAULT 0.0,
  `leftAnkleZ` DOUBLE NULL DEFAULT 0.0,
  `leftFootX` DOUBLE NULL DEFAULT 0.0,
  `leftFootY` DOUBLE NULL DEFAULT 0.0,
  `leftFootZ` DOUBLE NULL DEFAULT 0.0,
  `rightHipX` DOUBLE NULL DEFAULT 0.0,
  `rightHipY` DOUBLE NULL DEFAULT 0.0,
  `rightHipZ` DOUBLE NULL DEFAULT 0.0,
  `rightKneeX` DOUBLE NULL DEFAULT 0.0,
  `rightKneeY` DOUBLE NULL DEFAULT 0.0,
  `rightKneeZ` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleX` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleY` DOUBLE NULL DEFAULT 0.0,
  `rightAnkleZ` DOUBLE NULL DEFAULT 0.0,
  `rightFootX` DOUBLE NULL DEFAULT 0.0,
  `rightFootY` DOUBLE NULL DEFAULT 0.0,
  `rightFootZ` DOUBLE NULL DEFAULT 0.0,
  `spineShoulderX` DOUBLE NULL DEFAULT 0.0,
  `spineShoulderY` DOUBLE NULL DEFAULT 0.0,
  `spineShoulderZ` DOUBLE NULL DEFAULT 0.0,
  `leftHandTipX` DOUBLE NULL DEFAULT 0.0,
  `leftHandTipY` DOUBLE NULL DEFAULT 0.0,
  `leftHandTipZ` DOUBLE NULL DEFAULT 0.0,
  `leftThumbX` DOUBLE NULL DEFAULT 0.0,
  `leftThumbY` DOUBLE NULL DEFAULT 0.0,
  `leftThumbZ` DOUBLE NULL DEFAULT 0.0,
  `rightHandTipX` DOUBLE NULL DEFAULT 0.0,
  `rightHandTipY` DOUBLE NULL DEFAULT 0.0,
  `rightHandTipZ` DOUBLE NULL DEFAULT 0.0,
  `rightThumbX` DOUBLE NULL DEFAULT 0.0,
  `rightThumbY` DOUBLE NULL DEFAULT 0.0,
  `rightThumbZ` DOUBLE NULL DEFAULT 0.0,
  PRIMARY KEY (`skeletonId`),
  INDEX `measurementFrameId_idx` (`measurementFrameId` ASC),
  UNIQUE INDEX `skeletonId_UNIQUE` (`skeletonId` ASC),
  CONSTRAINT `measurementFrameId2`
    FOREIGN KEY (`measurementFrameId`)
    REFERENCES `mfast`.`MeasurementFrame` (`measurementFrameId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mfast`.`Confidence_v2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mfast`.`Confidence_v2` (
  `confidenceId` INT NOT NULL AUTO_INCREMENT,
  `skeletonId` INT NULL DEFAULT NULL,
  `spineBase` FLOAT NULL DEFAULT 0.0,
  `spineMid` FLOAT NULL DEFAULT 0.0,
  `neck` FLOAT NULL DEFAULT 0.0,
  `head` FLOAT NULL DEFAULT 0.0,
  `leftShoulder` FLOAT NULL DEFAULT 0.0,
  `leftElbow` FLOAT NULL DEFAULT 0.0,
  `leftWrist` FLOAT NULL DEFAULT 0.0,
  `leftHand` FLOAT NULL DEFAULT 0.0,
  `rightShoulder` FLOAT NULL DEFAULT 0.0,
  `rightElbow` FLOAT NULL DEFAULT 0.0,
  `rightWrist` FLOAT NULL DEFAULT 0.0,
  `rightHand` FLOAT NULL DEFAULT 0.0,
  `leftHip` FLOAT NULL DEFAULT 0.0,
  `leftKnee` FLOAT NULL DEFAULT 0.0,
  `leftAnkle` FLOAT NULL DEFAULT 0.0,
  `leftFoot` FLOAT NULL DEFAULT 0.0,
  `rightHip` FLOAT NULL DEFAULT 0.0,
  `rightKnee` FLOAT NULL DEFAULT 0.0,
  `rightAnkle` FLOAT NULL DEFAULT 0.0,
  `rightFoot` FLOAT NULL DEFAULT 0.0,
  `spineShoulder` FLOAT NULL DEFAULT 0.0,
  `leftHandTip` FLOAT NULL DEFAULT 0.0,
  `leftThumb` FLOAT NULL DEFAULT 0.0,
  `rightHandTip` FLOAT NULL DEFAULT 0.0,
  `rightThumb` FLOAT NULL DEFAULT 0.0,
  PRIMARY KEY (`confidenceId`),
  UNIQUE INDEX `skeletonId_UNIQUE` (`confidenceId` ASC),
  INDEX `confidenceId_idx` (`skeletonId` ASC),
  CONSTRAINT `confidenceSkeletonId`
    FOREIGN KEY (`skeletonId`)
    REFERENCES `mfast`.`Skeleton_v2` (`skeletonId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
